# Generated by Django 5.2.7 on 2025-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
