# Generated by Django 5.2.7 on 2025-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
