# Generated by Django 5.2.7 on 2025-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_external_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='external_url',
            new_name='buy_url',
        ),
        migrations.AddField(
            model_name='book',
            name='info_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
